#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./scripts/render-chat.sh <session-id>

Renders sessions/<id>/shared/chat/messages/*.md into sessions/<id>/shared/chat.md.
EOF
}

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

SESSION="$1"
TOP="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${TOP:-}" ]]; then
  echo "Not in a git repo." >&2
  exit 1
fi

resolve_main_worktree() {
  local top="$1"
  local common
  common="$(git -C "$top" rev-parse --git-common-dir 2>/dev/null || true)"
  if [[ -z "${common:-}" ]]; then
    echo "$top"
    return
  fi
  if [[ "$common" != /* ]]; then
    common="$top/$common"
  fi
  if [[ "$common" == */.git/worktrees/* ]]; then
    dirname "$(dirname "$(dirname "$common")")"
    return
  fi
  if [[ "$common" == */.git ]]; then
    dirname "$common"
    return
  fi
  echo "$top"
}

MAIN="$(resolve_main_worktree "$TOP")"

CHAT_DIR="$MAIN/sessions/$SESSION/shared/chat/messages"
CHAT_MD="$MAIN/sessions/$SESSION/shared/chat.md"
LOCK_DIR="$MAIN/sessions/$SESSION/artifacts/locks/render-chat.lock"

mkdir -p "$(dirname "$LOCK_DIR")"
mkdir -p "$CHAT_DIR"

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  echo "render-chat is locked: $LOCK_DIR" >&2
  exit 1
fi
trap 'rmdir "$LOCK_DIR" >/dev/null 2>&1 || true' EXIT

TMP="$(mktemp "$CHAT_MD.XXXXXX")"

{
  echo "# Shared Chat (Session: $SESSION)"
  echo ""
  echo "Generated by ./scripts/render-chat.sh from shared/chat/messages/."
  echo ""
  echo "## Thread"
  echo ""
  if compgen -G "$CHAT_DIR/*.md" >/dev/null; then
    for f in $(ls -1 "$CHAT_DIR"/*.md | sort); do
      echo ""
      cat "$f"
      echo ""
    done
  else
    echo "- 暂无消息"
    echo ""
  fi
} >"$TMP"

mv "$TMP" "$CHAT_MD"
echo "Rendered: $CHAT_MD"
