[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SessionName,

    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-MainWorktreeRoot {
    param(
        [Parameter(Mandatory = $true)][string]$StartDir
    )

    $resolved = (Resolve-Path $StartDir).Path
    try {
        $lines = @(git -C $resolved worktree list --porcelain 2>$null)
        foreach ($line in $lines) {
            if ($line -like "worktree *") {
                return ($line.Substring(9)).Trim()
            }
        }
    }
    catch {
        # Fall back to the current worktree root if git is unavailable.
    }

    return $resolved
}

$RepoRoot = Resolve-MainWorktreeRoot -StartDir $RepoRoot
$RepoRoot = (Resolve-Path $RepoRoot).Path

$sessionRoot = Join-Path (Join-Path $RepoRoot "sessions") $SessionName
if (-not (Test-Path $sessionRoot)) {
    throw "Session not found: $sessionRoot"
}

$chatDir = Join-Path (Join-Path (Join-Path $sessionRoot "shared") "chat") "messages"
$chatMd = Join-Path (Join-Path $sessionRoot "shared") "chat.md"

New-Item -ItemType Directory -Path $chatDir -Force | Out-Null

$locksDir = Join-Path (Join-Path $sessionRoot "artifacts") "locks"
New-Item -ItemType Directory -Path $locksDir -Force | Out-Null
$lockDir = Join-Path $locksDir "render-chat.lock"

if (Test-Path $lockDir) {
    throw "render-chat is locked: $lockDir"
}

New-Item -ItemType Directory -Path $lockDir -Force | Out-Null
try {
    $out = New-Object System.Collections.Generic.List[string]
    $out.Add("# Shared Chat (Session: $SessionName)")
    $out.Add("")
    $out.Add("Generated by ./scripts/render-chat.ps1 from shared/chat/messages/.")
    $out.Add("")
    $out.Add("## Thread")
    $out.Add("")

    $files = @(Get-ChildItem -Path $chatDir -File -Filter "*.md" | Sort-Object -Property Name)
    if ($files.Count -eq 0) {
        $out.Add("- 暂无消息")
        $out.Add("")
    }
    else {
        foreach ($f in $files) {
            $out.Add("")
            $out.Add((Get-Content -Path $f.FullName -Raw -Encoding utf8).TrimEnd())
            $out.Add("")
        }
    }

    Set-Content -Path $chatMd -Value ($out -join "`n") -Encoding utf8
    Write-Host "Rendered: $chatMd" -ForegroundColor Green
}
finally {
    Remove-Item -Path $lockDir -Recurse -Force -ErrorAction SilentlyContinue
}
